apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: harness-product-onboarding
  title: Product Onboarding
  description: New Product Onboarding under an existing Org
  tags:
    - account-management
    - solutions-factory
